version: '2'

services:
 transmission:
  build: 
     context: .
     dockerfile: Dockerfile.armhf
  privileged: true
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /your/storage/path/:/data
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=username
    - OPENVPN_PASSWORD=password
    - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
    - LOCAL_NETWORK=192.168.0.0/24

 proxy:
  build: ./proxy/Dockerfile.armhf
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
